#!/bin/sh

# SOURCE: https://github.com/GNOME/pitivi/blob/0fcc448e098d430f226bc6a2912a3909c2429400/build/flatpak/gst-transcoder-configure

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

which meson > /dev/null 2>&1
if [ $? != 0 ]
then
    echo "You should install mesonbuild to build gst-transcoder: http://mesonbuild.com/"
    echo "You can simply install it with:"
    echo "    $ sudo pip3 install meson"

    exit 1
fi

rm -Rf build > /dev/null 2>&1
mkdir build/ && cd build && meson ../ $@

cat <<EOF > $DIR/Makefile
all:
	cd build && ninja
install:
	cd build && ninja install
clean:
	rm -Rf build
	rm Makefile
EOF

