#!/bin/sh

# SOURCE: https://github.com/GNOME/pitivi/blob/0fcc448e098d430f226bc6a2912a3909c2429400/build/flatpak/py-configure

for i in "$@"
do
  case $i in
    --module=*)
    MODULENAME="${i#*=}"
    shift
    ;;
    *)
    ARGS="$ARGS $i"
    shift
    ;;
  esac
done


cat <<EOF > Makefile
all:
	echo "Nothing"
install:
	CXX=/usr/bin/g++ CC=/usr/bin/gcc PYTHONUSERBASE=/app/ pip3 install --user $MODULENAME
EOF

