#!/bin/sh

SCARLETT_DIR=$(realpath $(dirname $0)/../../)

function generate_path_and_completion_calls {
  echo "export PATH=$SCARLETT_DIR/bin:/app/bin:/usr/bin:\$PATH"
}

RCFILE=$SCARLETT_DIR/.bashrc
cp ~/.bashrc $RCFILE

echo "export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:/app/lib/" >> $RCFILE
echo "export PS1=[scarlettOS]\ \$PS1" >> $RCFILE
generate_path_and_completion_calls >> $RCFILE


echo "=============================="
echo "Entering own built environment"
echo "=============================="

bash --rcfile $RCFILE
