#!/usr/bin/with-contenv bash

usermod -u ${FIXUID} ${UNAME}
groupmod -g ${FIXGID} ${UNAME}
usermod -g ${FIXGID} ${UNAME}
find / -uid 1000 -exec chown ${UNAME} {} \;
find / -gid 1000 -exec chgrp ${UNAME} {} \;

sed -i "s,${UNAME}:x:1000:1000::/home/${UNAME}:/bin/bash,${UNAME}:x:${FIXUID}:${FIXGID}::/home/${UNAME}:/bin/bash," /etc/passwd
